name: Deploy Go IITT application 

on: 
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                go-version: 1.16
            - name: Cache Go modules
              uses: actions/cache@v3
              with:
                path: |
                  ~/go/pkg/mod
                  ~/.cache/go-build
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                restore-keys: |
                  ${{ runner.os }}-go-

            - name: Create .env file
              run: echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME}}" >> .env
            - name: Inserting space access key
              run: echo "SPACES_ACCESS_KEY=${{ secrets.SPACES_ACCESS_KEY}}" >> .env
            - name: Inserting secret key 
              run: echo "SPACES_SECRET_KEY=${{ secrets.SPACES_SECRET_KEY}}" >> .env
            - name: Inserting Vonage API Key
              run: echo "VONAGE_API_KEY=${{ secrets.VONAGE_API_KEY}}" >> .env
            - name: Inserting Vonage Secret Key
              run: echo "VONAGE_API_SECRET=${{ secrets.VONAGE_API_SECRET}}" >> .env
            - name: Login to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            - name: Build docker contianer
              run: docker build -t hemanthx5603/goiitt .
            - name: Push image to docker hub
              run: docker push hemanthx5603/goiitt:latest
    deploy:
        needs: build
        runs-on: self-hosted
        steps: 
            - name: Pruning docker instances 
              run: docker system prune -a -f
            - name: Pull the docker Image
              run: docker pull hemanthx5603/goiitt:latest 
            # - name: Stopping Docker Container
            #   run: docker stop go-app-container
            - name: Delete old image
              run: docker rm -f go-app-container 
            - name: Run Docker Container
              run: docker run -d -p 8080:8081 --name go-app-container hemanthx5603/goiitt

