name: Deploy Go IITT application 

on: 
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Create .env file
              run: echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME}}" >> .env
            - name: Inserting space access key
              run: echo "SPACES_ACCESS_KEY=${{ secrets.SPACES_ACCESS_KEY}}" >> .env
            - name: Inserting secret key 
              run: echo "SPACES_SECRET_KEY=${{ secrets.SPACES_SECRET_KEY}}" >> .env
            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME}} -password-stdin ${{ secrets.DOCKER_PASSWORD }}
            - name: Build docker image
              run: docker build -t hemanthx5603/goiitt .
            - name: Push image to docker hub
              run: docker push hemanthx5603/goiitt:latest
    deploy:
        needs: build
        runs-on: self-hosted
        steps: 
            - name: Pull the docker Image
              run: docker pull hemanthx5603/goiitt:latest
            - name: Delete old container
              run: docker rm -f go-app-container 
            - name: Run Docker Container
              run: docker run -d -p 8080:8081 --name go-app-container hemanthx5603/goiitt

